kind: Deployment
metadata:
  name: hello-world-deploy
  labels:
    app: hello-world
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: binhyu17/myyweb
        ports:
        - containerPort: 8080