- hosts: localhost
- hosts: localhost
  connection: local
  
  tasks:
  - name: Create & Start Container
    docker_container:
      name: myweb
      image: "binhyu17/myhello"
      state: started
      ports:
      - "80:8080"